# Site settings
title: "Chad Nierenhausen"
email: chad.nierenhausen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 "A place for me to post reminders to myself about the things I do."
baseurl: ""
#host: 0.0.0.0
url: "http://chadnierenhausen.com"
title_description: "Web Development, Blogging, and Other Stuff I Do"
title_image: "images/bio.jpg"
google_analytics: "UA-64536435-1"
disqus_account:
github_repository: https://github.com/cnieren/blag
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: TheWicker12
github_username:  cnieren
linkedin_link: cnieren
google_plus_link:
stackoverflow_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/TheWicker12\">Chad Nierenhausen</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/cnieren\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
highlighter: pygments
exclude: [vendor]
