baseURL = "https://chadnierenhausen.com"
title = "Chad Nierenhausen"
theme = "cnieren"
languageCode = "en-us"

[pagination]
    pagerSize = 5
    path = "posts"


[permalinks]
    page = "/:slug/"
    posts = "/posts/:title"

[params]
    colorscheme = "solarized"
    tagline = "Technology Leader, Developer, Amateur Chef, Aspiring Maker"
    footerLeft = "Made with <i class=\"fas fa-heart\"></i> by Chad Nierenhausen"
    footerRight = "</> on <a href=\"http://github.com/cnieren\">Github</a> <i class=\"fab fa-github-alt\"></i>"
    description = "Chad Nierenhausen's Blog"
    keywords = "home, blog, chad, nierenhausen, chad nierenhausen"

    email = "chad.nierenhausen@gmail.com"
    github = "cnieren"
    twitter = "@TheWicker12"
    linkedin = "cnieren"
    ganalytics = "UA-64536435-1"
    gravatar = "https://s.gravatar.com/avatar/e13f7ee785d37b819842851e71d2ad22?s=150"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[menu]
    [[menu.main]]
    identifier  = "home"
    name        = "home"
    url         = "/"
    weight      = 1

    [[menu.main]]
    identifier  = "resume"
    name        = "resume"
    url         = "/resume/"
    weight      = 0

    # [[menu.main]]
    # identifier  = "about"
    # name        = "about"
    # url         = "/about/"
    # weight      = 2

[deployment]
    [[deployment.targets]]
    name = "aws"
    URL = "s3://chadnierenhausen.com?region=us-west-2"
    cloudFrontDistributionID = "E2F1VEZR0VQ1P6"