# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Cnieren"
license = "MIT"
licenselink = "https://github.com/cnieren/cnieren/blob/master/LICENSE.md"
description = "Hugo theme for my blog"
homepage = "https://www.chadnierenhausen.com/"
tags = ["hugo", "blog", "cnieren"]
features = ["blog"]
min_version = 0.14

[author]
  name = "Chad Nierenhausen"
  homepage = "https://chadnierenhausen.com"
