# Site settings
title: The Blag
email: TheWicker12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for me to post reminders to myself about the things I do.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: TheWicker12
github_username:  cnieren

# Build settings
markdown: kramdown
