# Site settings
title: Chad Nierenhausen
email: TheWicker12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for me to post reminders to myself about the things I do.
host: 0.0.0.0
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chadnierenhausen.com" # the base hostname & protocol for your site
twitter_username: TheWicker12
github_username:  cnieren

# Build settings
markdown: kramdown
permalink: "/:year/:month/:title"
highlighter: pygments
